### ISSUE TITLE
user's c19nGroups circles dont appear

### ISSUE THREAD

**Issue by noyg123** [linnovate/circles#2]
user's c19nGroups circles appear in the DB but not appear when i use the request in swagger.
For example, for user  "t4556@gmail.com" appear in the DB:
"c19nGroups1" : [
            ObjectId("57cbc2d82fbdfc1f4241d864")
        ],

but does not appear in the response (test on swagger).

**Comment by rivkatzur** [comment]
@noyg123 

User object from db
{
    "_id" : ObjectId("57b94ca9deb4713e0d3a9fbb"),
    "id" : "t4556@gmail.com",
    "circles" : {
        "c19nGroups2" : [ ],
        "c19nGroups1" : [
            ObjectId("57b94ca1deb4713e0d3a9f92")
        ],
        "c19n" : [
            ObjectId("57b94ca1deb4713e0d3a9fa9")
        ]
    },
    "displayName" : "Linnovate/department3/job1",
    "__v" : 0
}

c19nGroups1 Circle object from db
{
    "_id" : ObjectId("57b94ca1deb4713e0d3a9f92"),
    "circleId" : "614063",
    "circleType" : "c19nGroups1",
    **"isActive" : false,**
    "name" : "C19nGroup1_4",
    "updatedAt" : ISODate("2016-09-07T06:43:00.722Z"),
    "__v" : 0,
    "createdAt" : ISODate("2016-08-21T06:39:29.528Z")
}
**When isActive = false circle should not appear in the response.**
